---
- Waveform:
    Polarity : 1
    TimeScale: 4
    PeakThreshold: 8
- AnalysisWindow:
    Start   : 200
    Stop    : 290
    Baseline: 50
- Filtering:
    MovingAveragePoints: 2
    FFTCutoffFrequency : 360
- Histogram:
    NumberOfBins:  90
    LowerRange  :  -5
    UpperRange  :  85
    LandauFit  : False
    GaussianFit: False
    
