---
- Waveform:
    Polarity : -1
    TimeScale: 0.8
    PeakThreshold: 10
- AnalysisWindow:
    Start   : 950
    Stop    : 1400
    Baseline: 250
- Filtering:
    MovingAveragePoints: 3
    FFTCutoffFrequency : 375
- Histogram:
    NumberOfBins: 150
    LowerRange  :  -5
    UpperRange  : 145
    LandauFit  : False
    GaussianFit: False
    
