---
- Waveform:
    Polarity : 1
- AnalysisWindow:
    Start   : 650
    Stop    : 900
    Baseline: 250
- Filtering:
    MovingAveragePoints: 12
    FFTCutoffFrequency : 396
- Histogram:
    NumberOfBins: 100
    LowerRange  :  -5
    UpperRange  :  75
    LandauFit  : False
    GaussianFit: False
    
