---
- DeviceSettings:
   typeDev: '6000'
   numDev: '1' 
- DaqSettings:
    Mode: 1 
    preSamples: 500 
    postSamples: 1500 
    Tbase: 2 
    fName: '6000_BeamtTest_Apr25' 
    fPath: '/home/yfujii/work/data_2/'  #'/home/comet/work/data/' 
    Nevents: 200
    Nsubruns: 500
- ChannelSettings:
    Vrange: [4,4,4,4,6,6] 
    Rstatus: '1111' 
    Tstatus: '000001' 
    Tsimple: 5 
    Tthresh: [0,0,0,0,1000,1000]
    Polarity: [1,1,1,1,1,1] 
