---
- DeviceSettings:
   typeDev: '6000'
   numDev: '1' 
- DaqSettings:
    Mode: 1 
    preSamples: 2000 
    postSamples: 2000 
    Tbase: 2 
    fName: 'Test_July2_6000_Counter2' 
    fPath: '/home/comet/work/data/Counter2TestJuly2' 
    Nevents: 10 
    Nsubruns: 100 
- ChannelSettings:
    Vrange: [4,4,4,4,6,6] 
    Rstatus: '1111' 
    Tstatus: '110000' 
    Tsimple: 0 
    Tthresh: [-20,-20,0,0,0,0]
    Polarity: [0,0,1,1,1,1] 
