---
- DeviceSettings:
   typeDev: '6000'
   numDev: '1' 
- DaqSettings:
    Mode: 2 
    preSamples: 2000 
    postSamples: 2000 
    Tbase: 2 
    fName: '6000_Test_Apr5' 
    fPath: '/home/comet/work/data/' 
    Nevents: 1 
    Nsubruns: 10 
- ChannelSettings:
    Vrange: [3,3,3,3,6,6] 
    Rstatus: '1111' 
    Tstatus: '100100' 
    Tsimple: 5 
    Tthresh: [20,0,0,20,0,0]
    Polarity: [1,1,1,1,1,1] 
