---
- DeviceSettings:
   typeDev: '6000'
   numDev: '1' 
- DaqSettings:
    Mode: 1 
    preSamples: 500 
    postSamples: 1500 
    Tbase: 2 
    fName: 'MPPC_DarkCurrent_May10_Test' 
    fPath: '/home/yfujii/work/data_2/'  #'/home/comet/work/data/' 
    Nevents: 1000
    Nsubruns: 2
- ChannelSettings:
    Vrange: [2,2,2,2,6,6] 
    Rstatus: '1000' 
    Tstatus: '000001' 
    Tsimple: 5 
    Tthresh: [0,0,0,0,100,25]
    Polarity: [1,1,1,1,1,1] 
