---
- DeviceSettings:
   typeDev: '3000' 
   numDev: '1' 
- DaqSettings:
    Mode: 1 
    preSamples: 100 
    postSamples: 300 
    Tbase: 2 
    fName: 'Test_June29__3000' 
    fPath: '/home/comet/work/data/' #'/home/comet/work/data/' 
    Nevents: 20
    Nsubruns: 10
- ChannelSettings:
    Vrange: [6,4,4,4,6,6] 
    Rstatus: '1111' 
    Tstatus: '100000' 
    Tsimple: 0 
    Tthresh: [50,1000,0,0,0,0] 
    Polarity: [1,1,1,1,1,1] 
